name: release
on:
  push:
    tags:
      - "v*"

env:
  VERSION: ${{ github.ref_name }}

jobs:
  release_exe:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: go-version
        run: |
          make print-go-version >> "$GITHUB_OUTPUT"

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ steps.go-version.outputs.result }}

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make release